name = "Autopay Feature Example"
created = "2025-01-15T10:00:00Z"

next_place_id = 4
next_affordance_id = 9

[[places]]
id = 1
name = "Invoice"

[[places.affordances]]
id = 1
name = "Turn on Autopay"
connects_to = 2

[[places.affordances]]
id = 2
name = "View Details"

[[places.affordances]]
id = 3
name = "Download PDF"

[[places]]
id = 2
name = "Setup Autopay"

[[places.affordances]]
id = 4
name = "CC Fields"
connects_to = 3

[[places.affordances]]
id = 5
name = "ACH Option"
connects_to = 3

[[places.affordances]]
id = 6
name = "Cancel"
connects_to = 1

[[places]]
id = 3
name = "Confirm"

[[places.affordances]]
id = 7
name = "Thank You Message"

[[places.affordances]]
id = 8
name = "Print Receipt"